      SUBROUTINE URAND(R)
      IMPLICIT DOUBLE PRECISION (A-H,K,O-Z)
      INTEGER ISEED, IA, IC, IM
      COMMON /RNG/ ISEED
      PARAMETER (IA=16807, IC=0, IM=2147483647)
      SAVE

      ISEED = MOD(IA * ISEED + IC, IM)
      IF (ISEED.LT.0) ISEED = ISEED + IM
      R = DBLE(ISEED) / DBLE(IM)

      RETURN
      END
